CREATE TABLE IF NOT EXISTS accounts (
    id SERIAL PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    logged_in SMALLINT NOT NULL DEFAULT 0,
    banned BOOLEAN NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS characters (
    id SERIAL PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts(id),
    world_id INTEGER NOT NULL,
    name TEXT UNIQUE NOT NULL,
    level SMALLINT NOT NULL DEFAULT 1,
    job INTEGER NOT NULL DEFAULT 0,
    hp INTEGER NOT NULL DEFAULT 50,
    max_hp INTEGER NOT NULL DEFAULT 50,
    mp INTEGER NOT NULL DEFAULT 50,
    max_mp INTEGER NOT NULL DEFAULT 50,
    exp BIGINT NOT NULL DEFAULT 0,
    meso BIGINT NOT NULL DEFAULT 0,
    map_id INTEGER NOT NULL DEFAULT 10000,
    position_x SMALLINT NOT NULL DEFAULT 0,
    position_y SMALLINT NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_characters_account ON characters(account_id);
