CREATE TABLE IF NOT EXISTS accounts (
    id SERIAL PRIMARY KEY,
    username VARCHAR(13) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    logged_in INTEGER NOT NULL DEFAULT 0,
    banned BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS characters (
    id SERIAL PRIMARY KEY,
    account_id INTEGER NOT NULL REFERENCES accounts(id) ON DELETE CASCADE,
    world_id INTEGER NOT NULL,
    name VARCHAR(13) NOT NULL,
    level SMALLINT NOT NULL DEFAULT 1,
    job INTEGER NOT NULL DEFAULT 0,
    str SMALLINT NOT NULL DEFAULT 4,
    dex SMALLINT NOT NULL DEFAULT 4,
    luk SMALLINT NOT NULL DEFAULT 4,
    int SMALLINT NOT NULL DEFAULT 4,
    hp INTEGER NOT NULL DEFAULT 50,
    mp INTEGER NOT NULL DEFAULT 50,
    max_hp INTEGER NOT NULL DEFAULT 50,
    max_mp INTEGER NOT NULL DEFAULT 50,
    exp BIGINT NOT NULL DEFAULT 0,
    meso BIGINT NOT NULL DEFAULT 0,
    map_id INTEGER NOT NULL DEFAULT 100000000,
    spawn_point INTEGER NOT NULL DEFAULT 0,
    position_x SMALLINT NOT NULL DEFAULT 0,
    position_y SMALLINT NOT NULL DEFAULT 0,
    gender INTEGER NOT NULL DEFAULT 0,
    skin_color INTEGER NOT NULL DEFAULT 0,
    face INTEGER NOT NULL DEFAULT 20000,
    hair INTEGER NOT NULL DEFAULT 30000,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_characters_account_id ON characters(account_id);
CREATE INDEX IF NOT EXISTS idx_characters_world_id ON characters(world_id);
