pub mod asset_loaders;
pub mod asset_source;
pub mod frames;
pub mod map;

use std::marker::PhantomData;
use bevy::{
    asset::{AssetLoader, LoadContext, io::Reader},
    ecs::lifecycle::Add,
    ecs::observer::On,
    prelude::*,
    sprite::{Anchor, Sprite},
};

/// Trait for types that can be built from a WZ node, with inline image loading.
/// Generated by `#[derive(WzAsset)]`.
pub trait WzAsset: Sized {
    /// File extension for this asset type, e.g. "mob", "npc", "portal-frames".
    const EXTENSION: &'static str;

    /// Convert an asset path like "wz://Mob/0100100.img.mob" to a WZ node path.
    fn asset_path_to_wz_path(asset_path: &str) -> String;

    /// Build self from a WZ node, loading images via `load_context`.
    fn wz_build(
        node: &wz::Node,
        load_context: &mut LoadContext<'_>,
        label_prefix: &str,
    ) -> Result<Self, wz::WzError>;
}

// ═══════════════════════════════════════════════════════════════════════
//  Generic loader — one loader for all WzAsset types
// ═══════════════════════════════════════════════════════════════════════

#[derive(Debug)]
pub struct WzAssetLoaderError(Box<dyn std::error::Error + Send + Sync>);

impl std::fmt::Display for WzAssetLoaderError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "WZ asset load error: {}", self.0)
    }
}

impl std::error::Error for WzAssetLoaderError {}

impl From<wz::WzError> for WzAssetLoaderError {
    fn from(e: wz::WzError) -> Self { Self(Box::new(e)) }
}

impl From<wz::source::WzSourceError> for WzAssetLoaderError {
    fn from(e: wz::source::WzSourceError) -> Self { Self(Box::new(e)) }
}

pub struct WzAssetLoader<A: WzAsset + 'static>(PhantomData<A>);

impl<A: WzAsset + 'static> TypePath for WzAssetLoader<A> {
    fn type_path() -> &'static str { core::any::type_name::<Self>() }
    fn short_type_path() -> &'static str { core::any::type_name::<Self>() }
}

impl<A: WzAsset + 'static> Default for WzAssetLoader<A> {
    fn default() -> Self { Self(PhantomData) }
}

impl<A: WzAsset + TypePath + Asset + 'static> AssetLoader for WzAssetLoader<A> {
    type Asset = A;
    type Settings = ();
    type Error = WzAssetLoaderError;

    async fn load(
        &self,
        _reader: &mut dyn Reader,
        _settings: &(),
        load_context: &mut LoadContext<'_>,
    ) -> Result<A, Self::Error> {
        let asset_path = load_context.path().path().to_string_lossy().to_string();
        let wz_path = A::asset_path_to_wz_path(&asset_path);
        let source = wz::source::default_source();
        let node = source.node(&wz_path)?;
        Ok(A::wz_build(&node, load_context, "")?)
    }

    fn extensions(&self) -> &[&str] {
        &[A::EXTENSION]
    }
}

pub fn set_sprite_bottom_left(trigger: On<Add, Sprite>, mut commands: Commands) {
    commands
        .entity(trigger.event().entity)
        .insert(Anchor::BOTTOM_LEFT);
}

/// Plugin that registers all WZ asset types and loaders.
pub struct WzAssetPlugin;

impl Plugin for WzAssetPlugin {
    fn build(&self, app: &mut App) {
        use asset_loaders::*;
        use crate::wz::map::WzMapAsset;
        use crate::wz::frames::WzFrameAnimationAsset;

        // WzAsset types — all use the generic WzAssetLoader
        app.init_asset::<WzMapAsset>()
            .init_asset_loader::<WzAssetLoader<WzMapAsset>>();

        app.init_asset::<WzFrameAnimationAsset>()
            .init_asset_loader::<WzAssetLoader<WzFrameAnimationAsset>>();
    }
}
