pub mod asset_loaders;
pub mod asset_source;

use bevy::{
    asset::LoadContext,
    ecs::lifecycle::Add,
    ecs::observer::On,
    prelude::*,
    sprite::{Anchor, Sprite},
};

/// Trait for types that can be built from a WZ node, with inline image loading.
/// Generated by `#[derive(WzAsset)]`.
pub trait WzAsset: Sized {
    fn wz_build(
        node: &wz::Node,
        load_context: &mut LoadContext<'_>,
        label_prefix: &str,
    ) -> Result<Self, wz::WzError>;
}

pub fn set_sprite_bottom_left(trigger: On<Add, Sprite>, mut commands: Commands) {
    commands
        .entity(trigger.event().entity)
        .insert(Anchor::BOTTOM_LEFT);
}

/// Plugin that registers all WZ asset types and loaders.
pub struct WzAssetPlugin;

impl Plugin for WzAssetPlugin {
    fn build(&self, app: &mut App) {
        use asset_loaders::*;

        // Image loader (wzimg)
        // NOTE: Image is already init_asset'd by ImagePlugin (part of DefaultPlugins).
        // We only register our custom loader.
        app.init_asset_loader::<WzImageLoader>();

        // UI sprite asset (image + origin bundled)
        app.init_asset::<WzUiSpriteAsset>()
            .init_asset_loader::<WzUiSpriteLoader>();

        // Singleton startup data assets
        app.init_asset::<WzPhysicsAsset>()
            .init_asset_loader::<WzPhysicsLoader>()
            .init_asset::<WzZMapAsset>()
            .init_asset_loader::<WzZMapLoader>()
            .init_asset::<WzSkillDatabaseAsset>()
            .init_asset_loader::<WzSkillDatabaseLoader>()
            .init_asset::<WzJobCatalogAsset>()
            .init_asset_loader::<WzJobCatalogLoader>()
            .init_asset::<WzActionListsAsset>()
            .init_asset_loader::<WzActionListsLoader>();

        // Character data assets
        app.init_asset::<WzCharBodyAsset>()
            .init_asset_loader::<WzCharBodyLoader>()
            .init_asset::<WzHairBodyAsset>()
            .init_asset_loader::<WzHairBodyLoader>()
            .init_asset::<WzEquipActionAsset>()
            .init_asset_loader::<WzEquipActionLoader>()
            .init_asset::<WzFaceExpressionAsset>()
            .init_asset_loader::<WzFaceExpressionLoader>();

        // UI bundle asset (caller-specified paths, single cacheable GET)
        app.init_asset::<WzUiBundleAsset>()
            .init_asset_loader::<WzUiBundleLoader>();

        // Portal frames asset
        app.init_asset::<WzPortalFramesAsset>()
            .init_asset_loader::<WzPortalFramesLoader>();

        // Logo frames asset (discovered at load time, nested dependencies)
        app.init_asset::<WzImageFramesAsset>()
            .init_asset_loader::<WzImageFramesLoader>();
    }
}
